# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# syntax=docker/dockerfile:1.4

# Builder stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies and build
COPY package.json package-lock.json tsconfig.json smithery.yaml ./
COPY src ./src
RUN npm install && npm run build

# Runtime stage
FROM node:lts-alpine AS runtime
WORKDIR /app

# Copy built application
COPY --from=builder /app/dist ./dist

# Copy package files to install production dependencies
COPY package.json package-lock.json ./

# Set production environment
ENV NODE_ENV=production

# Install only production dependencies and skip lifecycle scripts
RUN npm ci --omit=dev --ignore-scripts

# Start the MCP server
ENTRYPOINT ["node", "dist/index.js"]
