# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create work directory
WORKDIR /app

# Copy manifest files and tsconfig
COPY package.json package-lock.json tsconfig.json smithery.yaml ./

# Install dependencies without running prepare scripts
RUN npm ci --ignore-scripts

# Copy source
COPY . .

# Build TypeScript sources
RUN npm run build

# Use /app as allowed directory by default
ENTRYPOINT ["node", "dist/index.js"]
CMD ["/app"]
